pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cp -r * public/
    - mv public/public/ .tmp 2>/dev/null || true # Évite une boucle infinie
  artifacts:
    paths:
      - public
  only:
    - main